### ISSUE TITLE
Which platform manifest should be used?

### ISSUE THREAD

**Issue by amir28** [rockchip-software/TWRP#2]
Hello, I'm trying to compile twrp for rk3328 and android 9. and i don't know what platform manifast should I use. I tried 'github.com/minimal-manifest-twrp/platform_manifest_twrp_omni' but I get errors about some components are missing like hardware/realtek not found and somethings like that. I need to be clone by git clone before compile but i think the appropriate manifest may solve them.
Also I did not know how can solve last error which I got:
'''
including device/rockchip/rk3328/vendorsetup.sh
2022-01-08T11:29:19.7102081Z Traceback (most recent call last):
2022-01-08T11:29:19.7103854Z Your device can't be found in device sources..
2022-01-08T11:29:19.7106058Z   File "build/tools/roomservice.py", line 297, in <module>
2022-01-08T11:29:19.7107222Z     fetch_dependencies(device)
2022-01-08T11:29:19.7108513Z   File "build/tools/roomservice.py", line 248, in fetch_dependencies
2022-01-08T11:29:19.7109938Z     raise Exception("ERROR: could not find your device "
2022-01-08T11:29:19.7111275Z Exception: ERROR: could not find your device folder location, bailing out
'''

**Comment by cnwtttt** [comment]
You must pull rk3328_box_pie_release.xml's repo，this manifest is ok.
You should confirm you have permission.

**Comment by amir28** [comment]
Thank you for quick anwser. but you mean i need ask rockchip to permission for building TWRP? It seems not wisely because manifests just simplifies the compiling and manualy import all components is always possible.

**Comment by cnwtttt** [comment]
You need to have the source code for RK3328 Android 9.  Otherwise you won't compile TWRP properly.  TWRP needs to use some non-general functions on RK3328.

**Comment by amir28** [comment]
Got it. Thank you alot
